name: Android CI (disabled)

on:
  workflow_dispatch:
    inputs:
      run-build:
        description: 'Run build manually'
        default: 'true'

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "This workflow is disabled. Use flutter build workflow."
